apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ivx2no8y9-go 
  janus-idp.io/tekton: ivx2no8y9-go
  backstage.io/kubernetes-id: ivx2no8y9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ivx2no8y9-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  